[package]
name = "vcf-reformatter"
version = "0.1.0"
edition = "2024"
description = "Fast VCF file parser and reformatter with VEP annotation support"
authors = ["Flavio Lombardo <fl@flaviolombardo.site>"]
license = "MIT"
repository = "https://github.com/flalom/vcf-reformatter"
keywords = ["vcf", "bioinformatics", "genomics", "vep", "variant"]
categories = ["science", "command-line-utilities"]
readme = "README.md"

[dependencies]
flate2 = "1.1.2"
regex = "*"
rayon = "1.7"
num_cpus = "1.17.0"
clap = { version = "4.0", features = ["derive"] }
tempfile = "3.20.0"